import React from 'react';
import { Box, Paper, Typography, Stack, useTheme } from '@mui/material';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import BarChartIcon from '@mui/icons-material/BarChart';

const data = [
  { name: 'John Doe', sales: 4000 },
  { name: 'Jane Smith', sales: 3000 },
  { name: 'Alice Johnson', sales: 2000 },
  { name: 'Bob Brown', sales: 2780 },
  { name: 'Charlie Davis', sales: 1890 },
  { name: 'Eva Green', sales: 2390 },
];

const CustomTooltip = ({ active, payload, label }) => {
  if (active && payload && payload.length) {
    return (
      <Box
        sx={{
          backgroundColor: '#0f172a',
          color: '#ffffff',
          px: 1.5,
          py: 1,
          borderRadius: '8px',
          boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.2)',
          border: '1px solid rgba(255, 255, 255, 0.1)',
        }}
      >
        <Typography variant="body2" sx={{ fontWeight: 600, fontSize: '0.8rem', color: '#f8fafc' }}>
          {label}
        </Typography>
        <Typography variant="caption" sx={{ color: '#34d399', fontWeight: 600, fontSize: '0.775rem' }}>
          Revenue: ₹{payload[0].value.toLocaleString()}
        </Typography>
      </Box>
    );
  }
  return null;
};

const UserSalesChart = () => {
  const theme = useTheme();
  const isDark = theme.palette.mode === 'dark';

  return (
    <Paper
      elevation={0}
      sx={{
        backgroundColor: 'background.paper',
        borderRadius: '14px',
        border: `1px solid ${theme.palette.divider}`,
        boxShadow: '0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px -1px rgba(0, 0, 0, 0.05)',
        p: { xs: 1.5, sm: 1.75 },
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        transition: 'all 0.25s ease',
        '&:hover': {
          borderColor: 'primary.main',
          boxShadow: '0 4px 12px 0 rgba(0, 0, 0, 0.05)',
        },
      }}
    >
      {/* Header */}
      <Stack direction="row" justifyContent="space-between" alignItems="flex-start" sx={{ mb: 1 }}>
        <Box>
          <Typography variant="h6" sx={{ fontWeight: 700, color: 'text.primary', fontSize: '0.925rem', lineHeight: 1.25 }}>
            Employee Sales Performance
          </Typography>
          <Typography variant="body2" sx={{ color: 'text.secondary', fontSize: '0.725rem', mt: 0.25 }}>
            Revenue generated by team members
          </Typography>
        </Box>
        <Box
          sx={{
            width: 32,
            height: 32,
            borderRadius: '8px',
            backgroundColor: isDark ? 'rgba(59, 130, 246, 0.15)' : '#eff6ff',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            flexShrink: 0,
          }}
        >
          <BarChartIcon sx={{ fontSize: 18, color: '#3b82f6' }} />
        </Box>
      </Stack>

      {/* Bar Chart Area */}
      <Box sx={{ width: '100%', flexGrow: 1, minHeight: 180, maxHeight: 260, height: { xs: 200, sm: 220, md: 'calc(100vh - 365px)' } }}>
        <ResponsiveContainer width="100%" height="100%">
          <BarChart
            data={data}
            margin={{
              top: 10,
              right: 10,
              left: -15,
              bottom: 0,
            }}
          >
            <CartesianGrid strokeDasharray="3 3" stroke={isDark ? '#1e293b' : '#f1f5f9'} vertical={false} />
            <XAxis
              dataKey="name"
              tickLine={false}
              axisLine={{ stroke: isDark ? '#334155' : '#e2e8f0' }}
              tick={{ fill: theme.palette.text.secondary, fontSize: 10, fontWeight: 500 }}
              interval={0}
            />
            <YAxis
              tickLine={false}
              axisLine={false}
              tick={{ fill: theme.palette.text.secondary, fontSize: 10 }}
              tickFormatter={(val) => `₹${val >= 1000 ? val / 1000 + 'k' : val}`}
            />
            <Tooltip content={<CustomTooltip />} cursor={{ fill: isDark ? 'rgba(255, 255, 255, 0.05)' : 'rgba(241, 245, 249, 0.6)' }} />
            <Bar
              dataKey="sales"
              name="Sales"
              fill="#10b981"
              radius={[4, 4, 0, 0]}
              maxBarSize={32}
            />
          </BarChart>
        </ResponsiveContainer>
      </Box>
    </Paper>
  );
};

export default UserSalesChart;