import React from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';

const data = [
  { name: 'John Doe', sales: 4000 },
  { name: 'Jane Smith', sales: 3000 },
  { name: 'Alice Johnson', sales: 2000 },
  { name: 'Bob Brown', sales: 2780 },
  { name: 'Charlie Davis', sales: 1890 },
  { name: 'Eva Green', sales: 2390 },
];

const UserSalesChart = () => {
  return (
    <div style={{ width: '100%', height: 200 }}>
      <h2>Sales Generated by Employees</h2>
      <ResponsiveContainer width="100%" height="100%">
        <BarChart
          data={data}
          margin={{
            top: 20,
            right: 30,
            left: 20,
            bottom: 5,
          }}
        >
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="name" />
          <YAxis />
          <Tooltip />
          <Legend />
          <Bar dataKey="sales" fill="lightgreen" />
        </BarChart>
      </ResponsiveContainer>
    </div>
  );
};

export default UserSalesChart;